name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Standard:
    runs-on: ubuntu-latest
    name: Standard
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run StandardRB
        run: bin/standardrb
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run Prettier
        run: npx prettier --check .
