name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  SystemTests:
    runs-on: ubuntu-latest
    name: "System Tests"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run System Tests
        run: bin/rails test:system
  UnitTests:
    runs-on: ubuntu-latest
    name: "Unit Tests"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Unit Tests
        run: bin/rails test
